name = "MvtPointProcesses"
uuid = "29ad95c7-6704-4d51-8ead-909b792d765b"
authors = ["Jake Grainger"]
version = "0.1.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
